name: MaxBans
version: 1.0
main: org.maxgamer.maxbans.MaxBans

commands:
   ban:
      description: Bans a user, optionally for a duration
      usage: /ban <user> [duration] [message]

   unban:
      description: Unbans a user
      usage: /unban <user>
      
   mute:
      description: Mutes a user, optionally for a duration
      usage: /mute <user> [duration] [message]

   unmute:
      description: Unmutes a user
      usage: /unmute <user>

   kick:
      description: Kicks a user
      usage: /kick <player> [message]

   iplookup:
      description: Inspect information about a players most recent IP address
      usage: /iplookup <user>

   warn:
      description: Warn a player for misbehaviour
      usage: /warn <user> [message]

   lockdown:
      description: Prevent players from joining the server.
      usage: /lockdown <ALL|JOIN|NEW|OFF> [reason]