name: MaxBans
version: 1.0
main: org.maxgamer.maxbans.MaxBans

commands:
   ban:
      description: Bans a user, optionally for a duration
      usage: /ban <player> [duration] [message]
      
   mute:
      description: Mutes a user, optionally for a duration
      usage: /mute <player> [duration] [message]

   kick:
      description: Kicks a user
      usage: /kick <player> [message]

   iplookup:
      description: Inspect information about a players most recent IP address
      usage: /iplookup <player>